[versions]
widget = "0.0.3.24-20260130.100840-SNAPSHOT"
network = "0.0.1-20260129.150019-SNAPSHOT"

[plugins]

[libraries]
widget = { group = "com.codehong.library", name = "widget", version.ref = "widget" }
network = { group = "com.codehong.library", name = "network", version.ref = "network" }

[bundles]

